name: Manual run

on:
  workflow_dispatch:  
  # manual run from github website
  # no commit no push!

env:
  tg_channel_id: ${{ secrets.TG_CHANNEL_ID }}
  tg_token: ${{ secrets.TG_TOKEN }}
  ym_token: ${{ secrets.YM_TOKEN }}
  zv_token: ${{ secrets.ZV_TOKEN }}

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v5 (test)
        uses: actions/checkout@v5
      - name: Set up v6 (test) Python 3.14.0 (test)
        uses: actions/setup-python@v6
        with:
          python-version: "3.14.0"
      - name: Install dependencies (test)
        run: |
          python -m pip install --upgrade pip
          if [ -f 'Python Scripts/requirements.txt' ]; then pip install -r 'Python Scripts/requirements.txt'; fi
      - name: Execute py script
        run: python 'Python Scripts/AMR_LookApp_local.py'
      # - name: Commit files
      #   run: |
      #     git config --local user.email "mushroomoff@mail.ru"
      #     git config --local user.name "MushroomOFF"
      #     git add -A
      #     git commit -a -m "AMR LookApp autoupdate"
      # - name: Push changes
      #   uses: ad-m/github-push-action@master
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main